(function($) {
var thePage = $("#mainStoryContent");


thePage.html(thePage.html().replace(/Kiradech Aphibarnrat/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Kiradech_Aphibarnrat.shtml\' class=\'playerName\'>Kiradech Aphibarnrat</a>'));
thePage.html(thePage.html().replace(/Daniel Berger/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Daniel_Berger.shtml\' class=\'playerName\'>Daniel Berger</a>'));
thePage.html(thePage.html().replace(/Wesley Bryan/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Wesley_Bryan.shtml\' class=\'playerName\'>Wesley Bryan</a>'));
thePage.html(thePage.html().replace(/Angel Cabrera/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Angel_Cabrera.shtml\' class=\'playerName\'>Angel Cabrera</a>'));
thePage.html(thePage.html().replace(/Rafa Cabrera-Bello/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Rafa_Cabrera-Bello.shtml\' class=\'playerName\'>Rafa Cabrera-Bello</a>'));
thePage.html(thePage.html().replace(/Patrick Cantlay/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Patrick_Cantlay.shtml\' class=\'playerName\'>Patrick Cantlay</a>'));
thePage.html(thePage.html().replace(/Paul Casey/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Paul_Casey.shtml\' class=\'playerName\'>Paul Casey</a>'));
thePage.html(thePage.html().replace(/Kevin Chappell/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Kevin_Chappell.shtml\' class=\'playerName\'>Kevin Chappell</a>'));
thePage.html(thePage.html().replace(/Austin Cook/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Austin_Cook.shtml\' class=\'playerName\'>Austin Cook</a>'));
thePage.html(thePage.html().replace(/Fred Couples/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Fred_Couples.shtml\' class=\'playerName\'>Fred Couples</a>'));
thePage.html(thePage.html().replace(/Jason Day/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Jason_Day.shtml\' class=\'playerName\'>Jason Day</a>'));
thePage.html(thePage.html().replace(/Bryson DeChambeau/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Bryson_DeChambeau.shtml\' class=\'playerName\'>Bryson DeChambeau</a>'));
thePage.html(thePage.html().replace(/Jason Dufner/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Jason_Dufner.shtml\' class=\'playerName\'>Jason Dufner</a>'));
thePage.html(thePage.html().replace(/Harry Ellis/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Harry_Ellis.shtml\' class=\'playerName\'>Harry Ellis</a>'));
thePage.html(thePage.html().replace(/Tony Finau/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Tony_Finau.shtml\' class=\'playerName\'>Tony Finau</a>'));
thePage.html(thePage.html().replace(/Ross Fisher/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Ross_Fisher.shtml\' class=\'playerName\'>Ross Fisher</a>'));
thePage.html(thePage.html().replace(/Matthew Fitzpatrick/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Matthew_Fitzpatrick.shtml\' class=\'playerName\'>Matthew Fitzpatrick</a>'));
thePage.html(thePage.html().replace(/Tommy Fleetwood/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Tommy_Fleetwood.shtml\' class=\'playerName\'>Tommy Fleetwood</a>'));
thePage.html(thePage.html().replace(/Rickie Fowler/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Rickie_Fowler.shtml\' class=\'playerName\'>Rickie Fowler</a>'));
thePage.html(thePage.html().replace(/Sergio Garcia/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Sergio_Garcia.shtml\' class=\'playerName\'>Sergio Garcia</a>'));
thePage.html(thePage.html().replace(/Doug Ghim/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Doug_Ghim.shtml\' class=\'playerName\'>Doug Ghim</a>'));
thePage.html(thePage.html().replace(/Branden Grace/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Branden_Grace.shtml\' class=\'playerName\'>Branden Grace</a>'));
thePage.html(thePage.html().replace(/Adam Hadwin/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Adam_Hadwin.shtml\' class=\'playerName\'>Adam Hadwin</a>'));
thePage.html(thePage.html().replace(/Brian Harman/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Brian_Harman.shtml\' class=\'playerName\'>Brian Harman</a>'));
thePage.html(thePage.html().replace(/Tyrrell Hatton/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Tyrrell_Hatton.shtml\' class=\'playerName\'>Tyrrell Hatton</a>'));
thePage.html(thePage.html().replace(/Russell Henley/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Russell_Henley.shtml\' class=\'playerName\'>Russell Henley</a>'));
thePage.html(thePage.html().replace(/Charley Hoffman/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Charley_Hoffman.shtml\' class=\'playerName\'>Charley Hoffman</a>'));
thePage.html(thePage.html().replace(/Billy Horschel/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Billy_Horschel.shtml\' class=\'playerName\'>Billy Horschel</a>'));
thePage.html(thePage.html().replace(/Yuta Ikeda/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Yuta_Ikeda.shtml\' class=\'playerName\'>Yuta Ikeda</a>'));
thePage.html(thePage.html().replace(/Trevor Immelman/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Trevor_Immelman.shtml\' class=\'playerName\'>Trevor Immelman</a>'));
thePage.html(thePage.html().replace(/Dustin Johnson/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Dustin_Johnson.shtml\' class=\'playerName\'>Dustin Johnson</a>'));
thePage.html(thePage.html().replace(/Zach Johnson/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Zach_Johnson.shtml\' class=\'playerName\'>Zach Johnson</a>'));
thePage.html(thePage.html().replace(/Martin Kaymer/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Martin_Kaymer.shtml\' class=\'playerName\'>Martin Kaymer</a>'));
thePage.html(thePage.html().replace(/Si Woo Kim/ig, '<a href=\'http://www.augusta.com/masters/players/bios/SiWoo_Kim.shtml\' class=\'playerName\'>Si Woo Kim</a>'));
thePage.html(thePage.html().replace(/Kevin Kisner/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Kevin_Kisner.shtml\' class=\'playerName\'>Kevin Kisner</a>'));
thePage.html(thePage.html().replace(/Patton Kizzire/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Patton_Kizzire.shtml\' class=\'playerName\'>Patton Kizzire</a>'));
thePage.html(thePage.html().replace(/Brooks Koepka/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Brooks_Koepka.shtml\' class=\'playerName\'>Brooks Koepka</a>'));
thePage.html(thePage.html().replace(/Matt Kuchar/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Matt_Kuchar.shtml\' class=\'playerName\'>Matt Kuchar</a>'));
thePage.html(thePage.html().replace(/Bernhard Langer/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Bernhard_Langer.shtml\' class=\'playerName\'>Bernhard Langer</a>'));
thePage.html(thePage.html().replace(/Marc Leishman/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Marc_Leishman.shtml\' class=\'playerName\'>Marc Leishman</a>'));
thePage.html(thePage.html().replace(/Haotong Li/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Haotong_Li.shtml\' class=\'playerName\'>Haotong Li</a>'));
thePage.html(thePage.html().replace(/Yuxin Lin/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Yuxin_Lin.shtml\' class=\'playerName\'>Yuxin Lin</a>'));
thePage.html(thePage.html().replace(/Sandy Lyle/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Sandy_Lyle.shtml\' class=\'playerName\'>Sandy Lyle</a>'));
thePage.html(thePage.html().replace(/Hideki Matsuyama/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Hideki_Matsuyama.shtml\' class=\'playerName\'>Hideki Matsuyama</a>'));
thePage.html(thePage.html().replace(/Rory McIlroy/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Rory_McIlroy.shtml\' class=\'playerName\'>Rory McIlroy</a>'));
thePage.html(thePage.html().replace(/Phil Mickelson/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Phil_Mickelson.shtml\' class=\'playerName\'>Phil Mickelson</a>'));
thePage.html(thePage.html().replace(/Larry Mize/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Larry_Mize.shtml\' class=\'playerName\'>Larry Mize</a>'));
thePage.html(thePage.html().replace(/Francesco Molinari/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Francesco_Molinari.shtml\' class=\'playerName\'>Francesco Molinari</a>'));
thePage.html(thePage.html().replace(/Ryan Moore/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Ryan_Moore.shtml\' class=\'playerName\'>Ryan Moore</a>'));
thePage.html(thePage.html().replace(/Joaquin Niemann/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Joaquin_Niemann.shtml\' class=\'playerName\'>Joaquin Niemann</a>'));
thePage.html(thePage.html().replace(/Alex Noren/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Alex_Noren.shtml\' class=\'playerName\'>Alex Noren</a>'));
thePage.html(thePage.html().replace(/Jose Maria Olazabal/ig, '<a href=\'http://www.augusta.com/masters/players/bios/JoseMaria_Olazabal.shtml\' class=\'playerName\'>Jose Maria Olazabal</a>'));
thePage.html(thePage.html().replace(/Louis Oosthuizen/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Louis_Oosthuizen.shtml\' class=\'playerName\'>Louis Oosthuizen</a>'));
thePage.html(thePage.html().replace(/Matt Parziale/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Matt_Parziale.shtml\' class=\'playerName\'>Matt Parziale</a>'));
thePage.html(thePage.html().replace(/Pat Perez/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Pat_Perez.shtml\' class=\'playerName\'>Pat Perez</a>'));
thePage.html(thePage.html().replace(/Thomas Pieters/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Thomas_Pieters.shtml\' class=\'playerName\'>Thomas Pieters</a>'));
thePage.html(thePage.html().replace(/Ted Potter Jr/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Ted_PotterJr.shtml\' class=\'playerName\'>Ted Potter Jr</a>'));
thePage.html(thePage.html().replace(/Ian Poulter/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Ian_Poulter.shtml\' class=\'playerName\'>Ian Poulter</a>'));
thePage.html(thePage.html().replace(/Jon Rahm/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Jon_Rahm.shtml\' class=\'playerName\'>Jon Rahm</a>'));
thePage.html(thePage.html().replace(/Doc Redman/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Doc_Redman.shtml\' class=\'playerName\'>Doc Redman</a>'));
thePage.html(thePage.html().replace(/Patrick Reed/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Patrick_Reed.shtml\' class=\'playerName\'>Patrick Reed</a>'));
thePage.html(thePage.html().replace(/Justin Rose/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Justin_Rose.shtml\' class=\'playerName\'>Justin Rose</a>'));
thePage.html(thePage.html().replace(/Xander Schauffele/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Xander_Schauffele.shtml\' class=\'playerName\'>Xander Schauffele</a>'));
thePage.html(thePage.html().replace(/Charl Schwartzel/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Charl_Schwartzel.shtml\' class=\'playerName\'>Charl Schwartzel</a>'));
thePage.html(thePage.html().replace(/Adam Scott/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Adam_Scott.shtml\' class=\'playerName\'>Adam Scott</a>'));
thePage.html(thePage.html().replace(/Shubhankar Sharma/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Shubhankar_Sharma.shtml\' class=\'playerName\'>Shubhankar Sharma</a>'));
thePage.html(thePage.html().replace(/Webb Simpson/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Webb_Simpson.shtml\' class=\'playerName\'>Webb Simpson</a>'));
thePage.html(thePage.html().replace(/Vijay Singh/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Vijay_Singh.shtml\' class=\'playerName\'>Vijay Singh</a>'));
thePage.html(thePage.html().replace(/Jordan Spieth/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Jordan_Spieth.shtml\' class=\'playerName\'>Jordan Spieth</a>'));
thePage.html(thePage.html().replace(/Kyle Stanley/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Kyle_Stanley.shtml\' class=\'playerName\'>Kyle Stanley</a>'));
thePage.html(thePage.html().replace(/Brendan Steele/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Brendan_Steele.shtml\' class=\'playerName\'>Brendan Steele</a>'));
thePage.html(thePage.html().replace(/Henrik Stenson/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Henrik_Stenson.shtml\' class=\'playerName\'>Henrik Stenson</a>'));
thePage.html(thePage.html().replace(/Justin Thomas/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Justin_Thomas.shtml\' class=\'playerName\'>Justin Thomas</a>'));
thePage.html(thePage.html().replace(/Jhonattan Vegas/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Jhonattan_Vegas.shtml\' class=\'playerName\'>Jhonattan Vegas</a>'));
thePage.html(thePage.html().replace(/Jimmy Walker/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Jimmy_Walker.shtml\' class=\'playerName\'>Jimmy Walker</a>'));
thePage.html(thePage.html().replace(/Bubba Watson/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Bubba_Watson.shtml\' class=\'playerName\'>Bubba Watson</a>'));
thePage.html(thePage.html().replace(/Mike Weir/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Mike_Weir.shtml\' class=\'playerName\'>Mike Weir</a>'));
thePage.html(thePage.html().replace(/Bernd Wiesberger/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Bernd_Wiesberger.shtml\' class=\'playerName\'>Bernd Wiesberger</a>'));
thePage.html(thePage.html().replace(/Danny Willett/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Danny_Willett.shtml\' class=\'playerName\'>Danny Willett</a>'));
thePage.html(thePage.html().replace(/Gary Woodland/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Gary_Woodland.shtml\' class=\'playerName\'>Gary Woodland</a>'));
thePage.html(thePage.html().replace(/Tiger Woods/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Tiger_Woods.shtml\' class=\'playerName\'>Tiger Woods</a>'));
thePage.html(thePage.html().replace(/Ian Woosnam/ig, '<a href=\'http://www.augusta.com/masters/players/bios/Ian_Woosnam.shtml\' class=\'playerName\'>Ian Woosnam</a>'));

})(jQuery)
